name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline
      
      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
      - name: Build application
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SHADOW_DATABASE_URL: ${{ secrets.SHADOW_DATABASE_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NODE_ENV: production
      
      - name: Prepare deployment files
        id: prepare-files
        run: |
          if [ -d ".next/standalone" ]; then
            echo "Using standalone output"
            mkdir -p .next/standalone/.next
            cp -r .next/static .next/standalone/.next/
            cp -r public .next/standalone/
            
            # Create server.js for Linux App Service - Using an inline approach instead of heredoc
            echo '// Modified server.js for Linux Azure App Service' > .next/standalone/server.js
            echo 'const path = require("path");' >> .next/standalone/server.js
            echo '' >> .next/standalone/server.js
            echo '// Get port from environment (Linux App Service provides this)' >> .next/standalone/server.js
            echo 'const port = process.env.PORT || 8080;' >> .next/standalone/server.js
            echo 'process.env.NODE_ENV = "production";' >> .next/standalone/server.js
            echo 'process.chdir(__dirname);' >> .next/standalone/server.js
            echo '' >> .next/standalone/server.js
            echo '// Start the Next.js server' >> .next/standalone/server.js
            echo 'require("./server/server.js");' >> .next/standalone/server.js
            echo 'console.log(`Server running on port ${port} in production mode`);' >> .next/standalone/server.js
            
            echo "deployment_package=.next/standalone" >> $GITHUB_OUTPUT
          else
            echo "Using regular package"
            echo "Creating server.js wrapper for Linux"
            echo '// server.js wrapper for Linux App Service' > server.js
            echo 'const { exec } = require("child_process");' >> server.js
            echo 'const port = process.env.PORT || 8080;' >> server.js
            echo '' >> server.js
            echo '// Pass the PORT environment variable to Next.js' >> server.js
            echo 'const server = exec(`npx next start -p ${port}`);' >> server.js
            echo '' >> server.js
            echo 'server.stdout.on("data", (data) => {' >> server.js
            echo '  console.log(data);' >> server.js
            echo '});' >> server.js
            echo '' >> server.js
            echo 'server.stderr.on("data", (data) => {' >> server.js
            echo '  console.error(data);' >> server.js
            echo '});' >> server.js
            
            echo "deployment_package=." >> $GITHUB_OUTPUT
          fi
      
      - name: Optimize package
        run: |
          rm -rf .git .github node_modules/.cache
          npm prune --production
      
      - name: Deploy to Azure Web App
        id: deploy-to-azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'real-estate-crm-app-linux'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_LINUX }}
          package: ${{ steps.prepare-files.outputs.deployment_package }}
          clean: true
      
      - name: Deployment Status
        run: |
          if [ "${{ steps.deploy-to-azure.outcome }}" == "success" ]; then
            echo "✅ Deployment completed successfully!"
          else
            echo "❌ Deployment failed!"
            exit 1
          fi